---
- hosts: web
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Iniciar servicio de Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copiar la página web al servidor
      copy:
        src: index.html
        dest: /var/www/html/index.html
